name: Package Plugin

on:
  release:
    types:
      - created
      - updated

jobs:
  deploy:
    name: On Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Package Name
        id: package
        env:
          REPO: ${{ github.repository }}
        run: echo ::set-output name=PACKAGE::${REPO##*/}

      - name: PHP version
        run: php --version

      - name: Remove development files
        run: .github/scripts/cleanup.sh

      - name: Create Zip
        run: zip -r ${{ steps.package.outputs.PACKAGE }}.zip .

      - name: List Files
        run: ls -lah

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets{?name,label}
          asset_path: ./${{ steps.package.outputs.PACKAGE }}.zip
          asset_name: ${{ steps.package.outputs.PACKAGE }}.zip
          asset_content_type: application/zip
