name: Build Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    name: On Push to Master
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Package Name
        id: package
        env:
          REPO: ${{ github.repository }}
        run: echo ::set-output name=PACKAGE::${REPO##*/}

      - name: PHP version
        run: php --version

      - name: Remove development files
        run: .github/scripts/cleanup.sh

      - name: List Files
        run: ls -lah

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.package.outputs.PACKAGE }}
          path: ./
